### ISSUE TITLE
Splash screen shows for a brief moment and then moves to a loading indicator

### ISSUE THREAD

**Issue by dharding** [covid-alert-ny/covid-green-app#141]
The app shows a splash screen only while react native is initialized. It then moves into RN and shows a purple screen with a loading indicator. Perhaps this should retain the splash screen while the RN app actually loads the necessary information to display the first screen.

**Comment by ahurworth** [comment]
We need to show the branded elements on the splash screen up until we transition to the NY COVID Data tab.  We are not seeing them at all in build 17.

**Comment by floridemai** [comment]
@dharding @ahurworth I'll take care of this.

**Comment by floridemai** [comment]
@ahurworth This should be addressed in the next build 👍

**Comment by ahurworth** [comment]
I'm still seeing issues @floridemai .  On iOS I'm still seeing the splash screen logo appear twice.  On Android (Pixel) it only appears once, but feels very quick.

Screen recording of the experience on iOS (iPhone SE):
[ScreenRecording_09-08-2020 11:41.MP4.zip](https://github.com/project-vagabond/covid-green-app/files/5189356/ScreenRecording_09-08-2020.11.41.MP4.zip)

**Comment by helloantoine** [comment]
Same on my device. @floridemai Is this an issue with loading screen vs splash screen?

**Comment by JohnAGill** [comment]
This has been addressed and will be in the next build

**Comment by ahurworth** [comment]
I will close this ticket and re-open a new one for 1.1.
Android's splash screen isn't quite there yet unfortunately.
