### ISSUE TITLE
Health Log Generates Multiple Entries

### ISSUE THREAD

**Issue by ahurworth** [covid-alert-ny/covid-green-app#492]
A participant in the SUNY study over the weekend reported multiple entries into the Health Log when submitting symptoms.

![image](https://user-images.githubusercontent.com/68069959/93826245-d1686480-fc34-11ea-8a74-1bc883d05f9f.png)

Diagnostics: 
App Version: 1.0.0.41
Device: iPhone 8
OS version: ios 14.0
Closeness sensing status: active
Notifications: Allowed
ENS Details: {"c":true,"s":true,"st":{"state":"active"},"e":true,"p":{"exposure":"allowed","notifications":"allowed"},"a":"granted","cn":0}

**Comment by AlanSl** [comment]
Two questions:

 - @ahurworth Do we have any details about how the participant did this or what they were doing? I've tried to replicate and can only find one way to recreate a screenshot like that, which is to change timezones between one check and the next (which is something we wouldn't want to prevent). If possible it'd be good to rule out, for example, the possibility that this participant visited family in another timezone during the trial and checked in on the plane.
 - @floridemai I know we tested this a lot before iOS 14 was released; have we tested the check-in flow against back-swipe gestures specifically on iOS 14, in case the history behaviour is different?

**Comment by floridemai** [comment]
@AlanSl I don't think we did that, but we should not be able  to swipe back once the user checked-in for the day.

**Comment by ahurworth** [comment]
Checking with the user...

**Comment by AlanSl** [comment]
@denisedresbach Can you find a way to replicate this?

I've tried all sorts of things around setting the device date to days in the future, setting it to almost midnight and having the date change during check in, closing the app or using device back button during check in, etc, but it seems robust to me. The only way I can find is setting the device date so the check-ins are legitimately done on different days according to the device clock then changing time zone so they appear to have been the same day.

**Comment by denisedresbach** [comment]
@AlanSl I will give it a try.

**Comment by denisedresbach** [comment]
@AlanSl I can definitely reproduce this issue by changing the device date. But sounds like you already covered this and really just want to know if there is another way? 
1. Change date to 23rd, open app and check-in 
2. Change date to 24th, open app and do not check-in
3. Change date back to 23rd, check-in again

**Comment by AlanSl** [comment]
@denisedresbach Yes the going back in time part there is not something a user could normally do without intentionally tinkering with their device settings. The date changes are intended as a way we can simulate a user leaving the app unused for an amount of time then coming back to it.

**Comment by denisedresbach** [comment]
@AlanSl Got it! Android and iOS
If you tap multiple times on the continue button it will duplicate the symptoms.
1. Go to Check-in
2. Select symptoms
3. Tap continue really fast 
Results: You will see a couple screens fly by and after clicking Done you will see duplicated symptoms for same day.

![IMG_0164](https://user-images.githubusercontent.com/69995161/93946061-1e0f7680-fced-11ea-99f1-d97da05be250.PNG)

**Comment by AlanSl** [comment]
Thanks for cracking that one @denisedresbach !

We've addressed it in https://github.com/project-vagabond/covid-green-app/pull/507 and it should be fixed in build 46.

**Comment by ahurworth** [comment]
@denisedresbach Please can you review this and close if satisfied?  I'm not seeing the issue anymore, but I'm not confident I'm mimic'ing the repro steps exactly.

**Comment by denisedresbach** [comment]
@AlanSl @ahurworth 
Gave it a try on my Android build 1.0.0.46 - Same goes for iOS
FAIL -I was able to reproduce the issue still with the "I'm feeling well" button.
PASS -Tested the symptoms path and that does look good.

**Comment by AlanSl** [comment]
Gah! Can't believe I missed that. I'm on it now.

**Comment by AlanSl** [comment]
Done and will be in build 47 @denisedresbach feel free to close this if it passes retest

**Comment by ahurworth** [comment]
Since I have not been able to repro this, I'm unassigning myself.  @denisedresbach Please close this if it's looking good.

**Comment by denisedresbach** [comment]
Looks good! Tested on iOS and Android and no longer able to duplicate daily symptoms. 1.0.0.48
