### ISSUE TITLE
DOH UAT - County Selection Causes Fatal App Crash (CRITICAL)

### ISSUE THREAD

**Issue by kevin-sheldon** [covid-alert-ny/covid-green-app#75]
Build: 1.0.0 (13)
OS: Both iOS and Android

When toggling to the different county charts on the NY COVID Data screen for the counties Warren, Washington, Westchester, Wyoming and Yates, the app crashes completely. Attempts to restart app are met with a blank purple screen (Android), and a blank white screen (iOS). Restart of device did not fix. Uninstalling and redownloading the app was needed to return back to normal functionality. Clearing data from the Android Settings menu for the COVID app also allowed it to start again, but in default state. Clearing only the cached data from the Android Settings menu for the COVID app did not fix the issue.

**Comment by floridemai** [comment]
@kevin-sheldon The crash happens because of missing stats data for the following counties: `Warren`, `Washington`, `Wayne`, `Westchester`, `Wyoming`, `Yates`.

What I did?
* Currently chasing to see why this happened, and get it fixed. Will ping here when is fixed.
* Added some code to protect against missing that so that the app doesn't crash if this happens in the future. Simply the graphs cards won't be shown. PR here: https://github.com/project-vagabond/covid-green-app/pull/83

**Comment by floridemai** [comment]
@kevin-sheldon Data source issue was found and fixed here: https://github.com/project-vagabond/covid-green-regional-lambdas/pull/13. As soon as that's deployed data should be available for the problematic states. In any case, the app should not be crashing anymore.
Assigning back to you :)

**Comment by davidjharding** [comment]
@floridemai did the app get updated to not crash when there is missing data?

**Comment by davidjharding** [comment]
Confirmed that the data is still missing and the app no longer crashes.

**Comment by kevin-sheldon** [comment]
@dharding I am going to log new bug to determine why data is missing for several counties.

**Comment by floridemai** [comment]
@kevin-sheldon No need for that. The bug has been found and address. It's now a matter of deploying. On the other hand it's no harm in having it as a item to be checked off.

> @kevin-sheldon Data source issue was found and fixed here: [project-vagabond/covid-green-regional-lambdas#13](https://github.com/project-vagabond/covid-green-regional-lambdas/pull/13). As soon as that's deployed data should be available for the problematic states. In any case, the app should not be crashing anymore.
> Assigning back to you :)
