### ISSUE TITLE
Chart data does not seem accurate

### ISSUE THREAD

**Issue by fahd-arshad** [covid-alert-ny/covid-green-app#79]
Please ensure that the latest data is picked up. The API is showing data from 8/25, but the in-app charts are only showing data through 8/22. 

The charts data is not currently tying up with what the API reads out. E.g., Total persons tested is showing a value of <60k for 8/22. The actual value as per the API is 74,043. Please double-check the data and perhaps the alignment with the date labels.

**Comment by AlanSl** [comment]
Should be fixed in the next build now https://github.com/project-vagabond/covid-green-app/pull/87 is in

**Comment by AlanSl** [comment]
FYI the data I'm getting from the API currently is different to what is quoted in the comment above, e.g. `68407` for tests on August 22, and no 74043. The charts do reflect the API data they receive which is currently (statewide):

```js
  '2020-08-17T00:00:00.000': {
    cumulative_number_of_positives: 389007,
    cumulative_number_of_tests: 6637985,
    new_positives: 596,
    total_number_of_tests: 61092
  },
  '2020-08-18T00:00:00.000': {
    cumulative_number_of_positives: 389615,
    cumulative_number_of_tests: 6713048,
    new_positives: 608,
    total_number_of_tests: 75063
  },
  '2020-08-19T00:00:00.000': {
    cumulative_number_of_positives: 390191,
    cumulative_number_of_tests: 6788010,
    new_positives: 576,
    total_number_of_tests: 74962
  },
  '2020-08-20T00:00:00.000': {
    cumulative_number_of_positives: 390861,
    cumulative_number_of_tests: 6880362,
    new_positives: 670,
    total_number_of_tests: 92352
  },
  '2020-08-21T00:00:00.000': {
    cumulative_number_of_positives: 391478,
    cumulative_number_of_tests: 6967650,
    new_positives: 617,
    total_number_of_tests: 87288
  },
  '2020-08-22T00:00:00.000': {
    cumulative_number_of_positives: 392009,
    cumulative_number_of_tests: 7036057,
    new_positives: 531,
    total_number_of_tests: 68407
  },
  '2020-08-23T00:00:00.000': {
    cumulative_number_of_positives: 392395,
    cumulative_number_of_tests: 7093330,
    new_positives: 386,
    total_number_of_tests: 57273
  }
```

**Comment by fahd-arshad** [comment]
@AlanSl I am still seeing the in-app charts reporting data only through 8/22, not through 8/28. This needs to be addressed regardless.

Please see the two screenshots I am attaching. One is the visualizer from NYS Open Data, which is the source API - https://health.data.ny.gov/d/xdss-u53e/visualization:
![Data from NYS Open Data Visualizer](https://user-images.githubusercontent.com/68031284/91566054-f3055300-e8f7-11ea-9e40-3e2213fa74c0.png)

The second is the NYS DOH COVID Tracker - https://covid19tracker.health.ny.gov/views/NYS-COVID19-Tracker/NYSDOHCOVID-19Tracker-DailyTracker?%3Aembed=yes&%3Atoolbar=no&%3Atabs=n:
![Data from NYS DOH COVID Tracker](https://user-images.githubusercontent.com/68031284/91566171-1a5c2000-e8f8-11ea-90bc-a77d689e4323.png)

In both cases, they report 74043 for 8/22. This value doesn't appear in the dataset you are showing above at all. Can we please investigate why our call is returning a different number?

**Comment by AlanSl** [comment]
Ah, I see now, we're talking about different APIs.

https://api.dev.ctprox.health.ny.gov/api and https://api.prd.ctprox.health.ny.gov/api (the app data sources) are returning different data to https://health.data.ny.gov/ and  https://covid19tracker.health.ny.gov/

@segfault @mikegwhit Do you know why the app API might be returning different data to the NYS Open Data API? Could one be counting tests by UTC date and another by NYS date, for example?

**Comment by AlanSl** [comment]
Also @segfault and @mikegwhit is it possible for us to see the code that does the actual db lookup and calculates the values we get in the app?

**Comment by mikegwhit** [comment]
We ran through grabbing updated data from NYS by running the lambda locally.  This seemed to produce data consistent with the expected value above, e.g. 74043.  The presumption here then is that the hospital data rolls in and retroactively applies, e.g. on 8/24 new data for 8/22 arrives and 8/22 data is updated.  Proposed resolution is the ensure stats lambda is running correctly on cron therefore.

**Comment by AlanSl** [comment]
This appears to be fixed on the server side now that the lambda is running more frequently.

**Comment by fahd-arshad** [comment]
@AlanSl @mikegwhit thank you. The data looks much better now, but it seems to still be off by 1 day. For example, right now our screens show us the last label as 29 Aug, but that same bar on the two source sites above is Aug 30. You can easily tell because there were 3 days of high, nearly 100k tests, and then the latest bar is a dramatically lower number (closer to 60k). The shape and the data are all the same, but the label says 29 Aug when it should say 30 Aug.

**Comment by mikegwhit** [comment]
@fahd-arshad how are we doing on this?

**Comment by fahd-arshad** [comment]
@AlanSl @mikegwhit on build 31 the data is still showing as of 30 Aug. Today is 6 Sep. I visually compared it to the data on https://covid19tracker.health.ny.gov/views/NYS-COVID19-Tracker/NYSDOHCOVID-19Tracker-DailyTracker?%3Aembed=yes&%3Atoolbar=no&%3Atabs=n and it is definitely missing the last few days of data. Are we sure we are incrementing the end date as a variable to today/earliest data available?

**Comment by AlanSl** [comment]
@mikegwhit @jackmurdoch I see that we now get up-to-date data if I connect with a test token to the `dev` stats server on `https://api.dev.ctprox.health.ny.gov/api` - data matching https://covid19tracker.health.ny.gov/views/NYS-COVID19-Tracker/NYSDOHCOVID-19Tracker-DailyTracker?%3Aembed=yes&%3Atoolbar=no&%3Atabs=n in terms of most recent date and values.

![Screenshot_20200910-153221_COVID Alert NY](https://user-images.githubusercontent.com/29628323/92491164-d287a380-f1e9-11ea-89e9-f506e25ca46f.jpg)

Still getting the old data on `prd` though, no September data coming through. (also both `dev` and `prd` data are still 29 days not 30 but that's a lower priority than it not being up to date, we've patched up the UI so it looks okay with both 29 days and 30 days)

Hopefully this is useful for finding the problem on `prd`.

**Comment by mikegwhit** [comment]
This sounds like it will be more related to running that stats lambda on cron.  CC @segfault @rgormley

**Comment by segfault** [comment]
> This sounds like it will be more related to running that stats lambda on cron. CC @segfault @rgormley

The lambda is failing to run again as of 2-Sept. We're getting a 403, did the key change?

**Comment by AlanSl** [comment]
The data appears to have been successfully updating daily now, gives us enough data to display 30 days, and is accurate since we moved the averages calculation inside the app, so I think this is done now.

**Comment by helloantoine** [comment]
Looks good to me.
